version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: mansij
      POSTGRES_PASSWORD: password
      POSTGRES_DB: team_management_system
    ports:
      - "127.0.0.1:5432:5432"

  web:
    build: .
    restart: always
    command: sh -c "cd team_mgmt_sys && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db
